steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    secretEnv: ['DISCORD_TOKEN','DISCORD_TOKEN_2']
    args: ['-c', 'echo 1. $$DISCORD_TOKEN && echo 2. $$DISCORD_TOKEN_2']
#    args: ['build', '-t', 'gcr.io/$PROJECT_ID/parry-bot:latest', '--build-arg=_DISCORD_TOKEN', '.']
images: ['gcr.io/$PROJECT_ID/parry-bot']
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/DISCORD_TOKEN/versions/latest
      env: 'DISCORD_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/DISCORD_TOKEN/versions/latest
      env: 'DISCORD_TOKEN_2'
