steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - -c
      - |
        docker build -t us.gcr.io/${PROJECT_ID}/parry-bot:latest --build-arg token=$$DISCORD_TOKEN .
    secretEnv: ['DISCORD_TOKEN']
images: ['gcr.io/$PROJECT_ID/parry-bot']
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DISCORD_TOKEN/versions/latest
      env: 'DISCORD_TOKEN'
