name: hello_world_function
version: 0.4.0
description: Dart Functions Framework simple function example.
repository: https://github.com/GoogleCloudPlatform/functions-framework-dart
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  shelf: ^1.0.0
  nyxx: ^3.4.2

dev_dependencies:
  build_runner: ^2.0.0
  http: ^0.13.0
  test: ^1.15.7
  test_process: ^2.0.0
