name: discord_parry_bot
version: 1.0.0
description: Discord Parry bot for a private guild
repository: https://github.com/Praytic/discord-parry-bot
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  shelf: ^1.0.0
  nyxx: ^3.4.2
  logging: ^1.0.2

dev_dependencies:
  build_runner: ^2.0.0
  http: ^0.13.0
  test: ^1.15.7
  test_process: ^2.0.0
